---
title: "Analysis_of_pHHMer_Accessory_Enzymes"
author: "Dionne Martin"
output: pdf_document
---

#################### PREFACE ##########################
#Code for PCA, NMDS, and PERMANOVA/ simper test 
#of pHMMer results. ALL ENZYMES TEST RUN 
#carotenoid biosynthesis enzymes:
#Can percent idenitities give us an insight on 
#disimilarities in the pathway between habitats?  
#######################################################

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load packages and blastp raw hits data 
library(devtools)
library(ggbiplot)
library(readr)
phmmer_accessory <- read_csv("Cyano Carotenoids pHMMER Results - phmmer_accessory.csv")
#organize data to just raw hits and strain names 
#row.names(phmmer_accessory) = phmmer_accessory$Strain
#phmmer_accessory_matrix <- data.matrix(phmmer_accessory[c(3:16)])
phmmer_accessory_matrix = subset(phmmer_accessory, select=c(crtRa, crtRb, crtG, crtX, crtW, crtOa, crtN,crtP, crtQa, crtQb, cruF, crtM),row.names=1)
range(phmmer_accessory_matrix) #0 23

#analyze pca statistics to find proportion of variatiance explained by each gene 
pca_phmmer_accessory= prcomp(phmmer_accessory_matrix, center= TRUE, scale.= TRUE)
summary(pca_phmmer_accessory)
str(pca_phmmer_accessory)

#make groups based on habitat
habitat= phmmer_accessory$Habitat
```

```{r pca plots, echo=FALSE}
#png("PCA Plot of Carotenoid BLAST Hit .png", width=1000, height=1000)
ggbiplot(pca_phmmer_accessory,ellipse=TRUE,obs.scale = 3,var.scale = 1, groups=habitat) +
  scale_colour_manual(name="Habitat", values= c("saddlebrown", "darkorange1", "cornflowerblue", "deeppink", "red", "dark blue", "forest green", "gold", "darkmagenta", "black"))+
  ggtitle("PCA of pHMMer Accessory Enzymes")+
  theme_minimal()+
  theme(legend.position = "bottom")

#make the PCA plot with strain names (looks too messy with all names...)
#png("PCA Plot of Carotenoid BLAST Hit .png", width=1000, height=1000)
ggbiplot(pca_phmmer_accessory,labels= rownames(phmmer_accessory),ellipse=FALSE,obs.scale = 3,var.scale = 1, groups=habitat) +
  scale_colour_manual(name="Habitat", values= c("saddlebrown", "darkorange1", "cornflowerblue", "deeppink", "red", "dark blue", "forest green", "gold", "darkmagenta", "black"))+
  ggtitle("PCA of pHMMer Accessory Enzymes")+
  theme_minimal()+
  theme(legend.position = "bottom")
```

```{r NMDS, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load packages 
library(vegan)
library(ggplot2)
library(readr)

#prep data
phmmer_accessory <- read_csv("Cyano Carotenoids pHMMER Results - phmmer_accessory.csv")
#row.names(phmmer_accessory) = phmmer_accessory$Strain
phmmer_accessory_matrix = subset(phmmer_accessory, select=c(crtRa, crtRb, crtG, crtX, crtW, crtOa, crtN,crtP, crtQa, crtQb, cruF, crtM),row.names=1)
nmds_phmmer_accessory_habitat= as.data.frame(phmmer_accessory[,1:2])
#Do you need to transform your data? range should be 0-10 if not, use root function
range(phmmer_accessory_matrix) #0 23 

#make a distance matrix
phmmer_accessory_matrix_ds=vegdist(phmmer_accessory_matrix, method = 'euclidian')

#Run metaMDS on distance matrix
phmmer_accessory_nms=metaMDS(phmmer_accessory_matrix_ds, distance="euclidian",k=2,trymax=500)
phmmer_accessory_nms
#stress=0.08

#assign colors to habitat
cols <- nmds_pHMMER_habitat$Strain
cols[] <- c("saddlebrown", "darkorange1", "cornflowerblue", "deeppink", "red", "dark blue", "forest green", "gold", "darkmagenta", "black")
#Warning message:
#number of items to replace is not a multiple of replacement length

cols[nmds_phmmer_accessory_habitat$Habitat == c("freshwater")] <- "cornflowerblue"
cols[nmds_phmmer_accessory_habitat$Habitat == c("saltwater")] <- "dark blue"
cols[nmds_phmmer_accessory_habitat$Habitat == c("hot spring")] <- "deeppink"
cols[nmds_phmmer_accessory_habitat$Habitat == c("soil")] <- "forest green"
cols[nmds_phmmer_accessory_habitat$Habitat == c("cave")] <- "saddlebrown"
cols[nmds_phmmer_accessory_habitat$Habitat == c("desert")] <- "darkorange1"
cols[nmds_phmmer_accessory_habitat$Habitat == c("tropical")] <- "black"
cols[nmds_phmmer_accessory_habitat$Habitat == c("temperate")] <- "darkmagenta"
cols[nmds_phmmer_accessory_habitat$Habitat == c("symbiont")] <- "gold"
cols[nmds_phmmer_accessory_habitat$Habitat == c("rock")] <- "red"
pairs(character(nrow(nmds_phmmer_accessory_habitat$Strain, col=cols)))
                
habitatinfo= c(rep(phmmer_accessory$Habitat))
```

```{r NMDS plots, echo=FALSE}
#NMDS Plot With Species Names 
ordiplot(phmmer_accessory_nms, type="n")
orditorp(phmmer_accessory_nms,display="sites",labels=phmmer_accessory$Strain, col=cols ,air=0.00025)
par(xpd=TRUE)
#legend(0.6,0.25,legend =unique(nmds_small_habitat$Strain), fill=cols, border= "black")
#change coordinates of the legend for each specific graph
#legend(-0.4,-0.2, "stress = 0.13") 
#change coordinates and stress value for each specific graph
title(main="NMDS of pHMMer Accessory Enzymes")
scores <-
  scores(phmmer_accessory_nms, display = "sites", "species")
cent <-
  aggregate(scores ~ habitatinfo, data = nmds_phmmer_accessory_habitat, FUN = "mean")
names(cent) [-1] <- colnames(scores)
points(cent [,-1],
  pch = c( 8 , 8 , 8, 8),
  col = unique(cols),
  bg = c("black"),
  lwd = 3.0,
  cex = 2.0
)
                
#NMDS Plot with Points
plot(phmmer_accessory_nms)
points(phmmer_accessory_nms,display= "sites",pch=21, bg=cols) 
par(xpd=TRUE)
#legend(0,0, legend =#must be some type of vector with all habitats mentioned, fill=cols, border= "black")
#legend(-0.4,-0.2, "stress = 0.13") 
title(main="NMDS of pHMMer Accessory Enzymes")
scores <-
  scores(phmmer_accessory_nms, display = "sites", "species")
cent <-
  aggregate(scores ~ habitatinfo, data = nmds_phmmer_accessory_habitat, FUN = "mean")
names(cent) [-1] <- colnames(scores)
points(cent [,-1],
  pch = c( 8 , 8 , 8, 8),
  col = unique(cols),
  bg = c("black"),
  lwd = 3.0,
  cex = 2.0
)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#data prepartion 
rownames(phmmer_accessory_matrix) = phmmer_accessory$Strain
str(phmmer_accessory_matrix)
nmds_phmmer_accessory_habitat= as.data.frame(phmmer_accessory[,1:2])
str(nmds_phmmer_accessory_habitat)
                
#make a distance matrix
phmmer_accessory_matrix_ds=vegdist(phmmer_accessory_matrix, method = 'euclidian')
                
#Run metaMDS on distance matrix
phmmer_accessory_nms=metaMDS(phmmer_accessory_matrix_ds, distance="euclidian",k=2,trymax=500)
phmmer_accessory_nms
#stress=0.08
                
#Run PERMANOVA
pmv_phmmer_accessory = adonis(phmmer_accessory_matrix ~ habitat, data = nmds_phmmer_small_habitat, permutations = 999, method = 'euclidean')
pmv_phmmer_accessory
#PERMANOVA Results: Based off of the carotenoid genes being compared
#cyanobacterial strains differ statistically significant 
#between their habitats (p-value:0.001).
#Habitats explian 19.13% of the variance in the copy numbers of critical 
#carotenoid biosynthesis enzymes between cyanobacterial species. 
                
#Visualise the permanova
densityplot(permustats(pmv_phmmer_small))
                
#Distance Based Dispersion test 
bd_phmmer_accessory = betadisper(phmmer_accessory_matrix_ds, phmmer_small$Habitat)
boxplot(bd_phmmer_accessory)
anova(bd_phmmer_accessory) 
#F-Test: pvalue 0.003
permutest(bd_phmmer_accessory)
#permutation test: pvalue 0.008
#the significance of a permutation test is represented by its P-value. 
#The P-value is the probability of obtaining a result at least 
#as extreme as the test statistic given that the null hypothesis is true. 
                
#both the F-Test and permutation test show that 
#the avergae distance to the median for the 
#habitat data is not statistically significant. 
                
#simper test: determine which genes are responsible for the difference between 2 compared habitat groups 
simp_phmmer_accessory= simper(phmmer_accessory_matrix, group= phmmer_accessory_matrix$Habitat)
summary(simp_phmmer_accessory)
                
#Results of simper test
```
