---
title: "Analysis_BLASTp_Percent_Identities"
author: "Dionne Martin"
output: pdf_document
---

#################### PREFACE ##########################
#Code for PCA, NMDS, and PERMANOVA/ simper test 
#of the highest percent identity BLASTp hit of criticl 
#carotenoid biosynthesis enzymes: crtE, crtBa, crtBb,
#crtIa, crtIb, cruA, cruP, and crtL.
#Can percent idenitities give us an insight on 
#disimilarities in the pathway between habitats?  
#######################################################

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#PCA Plot 

#load packages and blastp raw hits data 
library(devtools)
library(ggbiplot)
library(readr)
percent <- read_csv("/bigdata/stajichlab/shared/projects/Cyanobacteria/Terresterial_Cyano/Cyano Carotenoids BLASTp Results - percent data.csv")
#organize data to just raw hits and strain names 
row.names(percent) = percent$Strain
percent_matrix <- data.matrix(percent[c(3:10)])
range(percent_matrix) #0 100 

#analyze pca statistics to find proportion of variatiance explained by each gene 
pca_percent= prcomp(percent_matrix, center= TRUE, scale.= TRUE)
summary(pca_percent)
str(pca_percent)
#crtE-0.45 crtBa-0.26 crtBb-0.09 crtIa-0.07
#crtIb-0.04 cruA-0.03 cruP-0.01 crtL-0.006


#make groups based on habitat
habitat= percent$Habitat


#try to make group colours, this should be added to plot code 
scale_colour_manual(name= "Habitat", values= c("brown", "dark orange", "blue", "pink", "red", "dark blue", "forest green", "dark yellow", "red", "black"))

#make the PCA plot with strains as points 
#png("PCA Plot of Carotenoid BLAST Hit .png", width=1000, height=1000)
ggbiplot(pca_percent,ellipse=TRUE,obs.scale = 3,var.scale = 1, groups=habitat) +
  scale_colour_manual(name="Habitat", values= c("saddlebrown", "darkorange1", "cornflowerblue", "deeppink", "red", "dark blue", "forest green", "gold", "darkmagenta", "black"))+
  ggtitle("PCA of BLASTp Percent Identities")+
  theme_minimal()+
  theme(legend.position = "bottom")

#make the PCA plot with strain names (looks too messy with all names...)
#png("PCA Plot of Carotenoid BLAST Hit .png", width=1000, height=1000)
ggbiplot(pca_percent,labels= rownames(percent),ellipse=FALSE,obs.scale = 3,var.scale = 1, groups=habitat) +
  scale_colour_manual(name="Habitat", values= c("saddlebrown", "darkorange1", "cornflowerblue", "deeppink", "red", "dark blue", "forest green", "gold", "darkmagenta", "black"))+
  ggtitle("PCA of BLASTp Percent Identities")+
  theme_minimal()+
  theme(legend.position = "bottom")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#NMDS Analysis

#load packages 
library(vegan)
library(ggplot2)
library(readr)

#prep data
percent <- read_csv("/bigdata/stajichlab/shared/projects/Cyanobacteria/Terresterial_Cyano/Cyano Carotenoids BLASTp Results - percent data.csv")
percent_matrix <- data.matrix(percent[c(3:10)])
nmds_percent_habitat= as.data.frame(percent[,1:2])
#Do you need to transform your data? range should be 0-10 if not, use root function
range((percent_matrix)^0.5) # 0-10

#make a distance matrix
percent_matrix_ds=vegdist(percent_matrix^0.5, method = 'euclidian')

#Run metaMDS on distance matrix
percent_nms=metaMDS(percent_matrix_ds, distance="euclidian",k=2,trymax=500)
percent_nms
#stress=0.071

#assign colors to habitat
cols <- nmds_percent_habitat$Strain
cols[] <- c("saddlebrown", "darkorange1", "cornflowerblue", "deeppink", "red", "dark blue", "forest green", "gold", "darkmagenta", "black")
#Warning message:
#number of items to replace is not a multiple of replacement length

cols[nmds_percent_habitat$Habitat == c("freshwater")] <- "cornflowerblue"
cols[nmds_percent_habitat$Habitat == c("saltwater")] <- "dark blue"
cols[nmds_percent_habitat$Habitat == c("hot spring")] <- "deeppink"
cols[nmds_percent_habitat$Habitat == c("soil")] <- "forest green"
cols[nmds_percent_habitat$Habitat == c("cave")] <- "saddlebrown"
cols[nmds_percent_habitat$Habitat == c("desert")] <- "darkorange1"
cols[nmds_percent_habitat$Habitat == c("tropical")] <- "black"
cols[nmds_percent_habitat$Habitat == c("temperate")] <- "darkmagenta"
cols[nmds_percent_habitat$Habitat == c("symbiont")] <- "gold"
cols[nmds_percent_habitat$Habitat == c("rock")] <- "red"
pairs(character(nrow(nmds_percent_habitat$Strain, col=cols)))
            
habitatinfo= c(rep(percent$Habitat))
```

```{r NMDS plots, echo =FALSE}
#NMDS Plot With Species Names 
ordiplot(percent_nms, type="n")
orditorp(percent_nms,display="sites",labels=percent$Strain, col=cols ,air=0.00025)
par(xpd=TRUE)
#legend(0.6,0.25,legend =unique(nmds_small_habitat$Strain), fill=cols, border= "black")
#change coordinates of the legend for each specific graph
#legend(-0.4,-0.2, "stress = 0.13") 
#change coordinates and stress value for each specific graph
title(main="NMDS of Raw BLASTp")
scores <-
  scores(percent_nms, display = "sites", "species")
cent <-
  aggregate(scores ~ habitatinfo, data = nmds_percent_habitat, FUN = "mean")
names(cent) [-1] <- colnames(scores)
points(cent [,-1],
pch = c( 8 , 8 , 8, 8),
col = unique(colors),
bg = c("black"),
lwd = 3.0,
cex = 2.0
)
                
#NMDS Plot with Points
plot(percent_nms)
points(percent_nms,display= "sites",pch=21, bg=cols) 
par(xpd=TRUE)
#legend(0.6,0.25,legend =habitatvec, fill=colvec, border= "black")
#legend(-0.4,-0.2, "stress = 0.13") 
title(main="NMDS of Raw BLASTp")
scores <-
  scores(percent_nms, display = "sites", "species")
cent <-
  aggregate(scores ~ habitatinfo, data = nmds_IPP_habitat, FUN = "mean")
names(cent) [-1] <- colnames(scores)
points(cent [,-1],
pch = c( 8 , 8 , 8, 8),
col = unique(colors),
bg = c("black"),
lwd = 3.0,
cex = 2.0
)
```

```{r stats, include=FALSE}
#data prepartion 
rownames(percent_matrix) = percent$Strain
str(percent_matrix)
nmds_percent_habitat= as.data.frame(percent[,1:2])
str(nmds_percent_habitat)
                
#make a distance matrix
percent_matrix_ds=vegdist(percent_matrix^0.5, method = 'euclidian')
                
#Run metaMDS on distance matrix
percent_nms=metaMDS(percent_matrix_ds, distance="euclidian",k=2,trymax=500)
percent_nms
#stress=0.0713
                
#Run PERMANOVA
pmv_percent = adonis(percent_matrix^0.5 ~ habitat, data = nmds_percent_habitat, permutations = 999, method = 'euclidean')
pmv_percent
#PERMANOVA Results: Based off of the carotenoid genes being compared
#cyanobacterial strains differ statistically significant 
#between their habitats (p-value:0.001).
#Habitats explian 34.65% of the variance in the copy numbers of critical 
#carotenoid biosynthesis enzymes between cyanobacterial species. 
                
#Visualise the permanova
densityplot(permustats(pmv_percent))
                
#Distance Based Dispersion test 
bd_percent = betadisper(percent_matrix_ds, percent$Habitat)
boxplot(bd_percent)
anova(bd_percent) 
#F-Test: pvalue 0.1353
permutest(bd_percent)
#permutation test: pvalue 0.392
#the significance of a permutation test is represented by its P-value. 
#The P-value is the probability of obtaining a result at least 
#as extreme as the test statistic given that the null hypothesis is true. 
                
#both the F-Test and permutation test show that 
#the average distance to the median for the 
#habitat data is not statistically significant. 
                
#simper test: determine which genes are responsible for the difference between 2 compared habiatat groups 
simp_percent= simper(percent_matrix^0.5, group= percent$Habitat)
summary(simp_percent)
```
