---
title: "p_ipp"
output: pdf_document
---

#################### PREFACE ##########################
#Code for PCA, NMDS, and PERMANOVA/ simper test 
#of pHMMer IPP results and Nicole's Habitat suggestion.  
#IPP biosynthesis enzymes: 
#Habitats: "soil", "aquatic", "hydroterrestrial", 
#######################################################

```{r PCA, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load packages and blastp raw hits data 
library(devtools)
library(ggbiplot)
library(readr)
p_ipp <- read_csv("Nicole's Habitat Data Sets - p_ipp.csv")
#organize data to just raw hits and strain names 
row.names(p_ipp) = p_ipp$Strain
p_ipp_matrix <- data.matrix(p_ipp[c(3:9)])
range(p_ipp_matrix) #0 10

#analyze pca statistics to find proportion of variatiance explained by each gene 
pca_p_ipp= prcomp(p_ipp_matrix, center= TRUE, scale.= TRUE)
summary(pca_p_ipp)
str(pca_p_ipp)

#make groups based on habitat
habitat_p_ipp= p_ipp$Habitat
```

```{r PCA plots, echo=FALSE}
#make the PCA plot with strains as points NEED TO DO PCA OF SEPERATE SETS OF GENES 
#png("PCA Plot of Carotenoid BLAST Hit .png", width=1000, height=1000)
ggbiplot(pca_p_ipp,ellipse=TRUE,obs.scale = 3,var.scale = 1, groups=habitat_p_ipp) +
  scale_colour_manual(name="Habitat", values= c("cornflowerblue", "forest green", "darkorange1", "saddlebrown"))+
  ggtitle("PCA of pHMMer IPP Enzymes -N")+
  theme_minimal()+
  theme(legend.position = "bottom")

#make the PCA plot with strain names (looks too messy with all names...)
#png("PCA Plot of Carotenoid BLAST Hit .png", width=1000, height=1000)
ggbiplot(pca_p_ipp,labels= rownames(p_ipp),ellipse=FALSE,obs.scale = 3,var.scale = 1, groups=habitat_p_ipp) +
  scale_colour_manual(name="Habitat", values= c("cornflowerblue", "forest green", "darkorange1", "saddlebrown"))+
  ggtitle("PCA of pHMMer IPP Enzymes -N")+
  theme_minimal()+
  theme(legend.position = "bottom")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load packages 
library(vegan)
library(ggplot2)
library(readr)

#prep data
p_ipp <- read_csv("Nicole's Habitat Data Sets - p_ipp.csv")
#organize data to just raw hits and strain names 
row.names(p_ipp) = p_ipp$Strain
p_ipp_matrix <- data.matrix(p_ipp[c(3:9)])
range(p_ipp_matrix) #0 10
nmds_p_ipp_habitat= as.data.frame(p_ipp[,1:2])

#make a distance matrix
p_ipp_matrix_ds=vegdist(p_ipp_matrix, method = 'euclidian')

#Run metaMDS on distance matrix
p_ipp_nms=metaMDS(p_ipp_matrix_ds, distance="euclidian",k=2,trymax=500)
p_ipp_nms
#stress=0.04

#assign colors to habitat
cols <- nmds_p_ipp_habitat$Strain
cols[] <- c("cornflowerblue", "forest green", "darkorange1", "saddlebrown","grey" )
#Warning message:
#number of items to replace is not a multiple of replacement length

cols[nmds_p_ipp_habitat$Habitat == c("aquatic")] <- "cornflowerblue"
cols[nmds_p_ipp_habitat$Habitat == c("soil")] <- "darkorange1"
cols[nmds_p_ipp_habitat$Habitat == c("hydroterrestrial")] <- "forest green"
cols[nmds_p_ipp_habitat$Habitat == c("subaerial")] <- "saddlebrown"
cols[nmds_p_ipp_habitat$Habitat == c("NA")] <- "grey"

pairs(character(nrow(nmds_p_ipp_habitat$Strain, col=cols)))

habitatinfo= c(rep(p_ipp$Habitat))
```

```{r NMDS plot, echo = FALSE}
#NMDS Plot With Species Names 
ordiplot(p_ipp_nms, type="n")
orditorp(p_ipp_nms,display="sites",labels=p_ipp$Strain, col=cols ,air=0.00025)
par(xpd=TRUE)
#legend(0.6,0.25,legend =unique(nmds_small_habitat$Strain), fill=cols, border= "black")
#change coordinates of the legend for each specific graph
#legend(-0.4,-0.2, "stress = 0.13") 
#change coordinates and stress value for each specific graph
title(main="NMDS of pHMMer IPP Results -N")
scores <-
  scores(p_ipp_nms, display = "sites", "species")
cent <-
  aggregate(scores ~ habitatinfo, data = nmds_p_ipp_habitat, FUN = "mean")
names(cent) [-1] <- colnames(scores)
points(cent [,-1],
  pch = c( 8 , 8 , 8, 8),
  col = unique(cols),
  bg = c("black"),
  lwd = 3.0,
  cex = 2.0
)
                
#NMDS Plot with Points
plot(p_ipp_nms)
points(p_ipp_nms,display= "sites",pch=21, bg=cols) 
par(xpd=TRUE)
#legend(0.6,0.25,legend =habitatvec, fill=colvec, border= "black")
 #legend(-0.4,-0.2, "stress = 0.13") 
title(main="NMDS of pHMMer IPP Results -N")
scores <-
  scores(p_ipp_nms, display = "sites", "species")
cent <-
  aggregate(scores ~ habitatinfo, data = nmds_p_ipp_habitat, FUN = "mean")
names(cent) [-1] <- colnames(scores)
points(cent [,-1],
  pch = c( 8 , 8 , 8, 8),
  col = unique(cols),
  bg = c("black"),
  lwd = 3.0,
  cex = 2.0
 )

```

```{r PERMANOVA, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#data prepartion 
row.names(p_ipp_matrix) = p_ipp$Strain
str(p_ipp_matrix)
nmds_p_ipp_habitat= as.data.frame(p_ipp[,1:2])
str(nmds_p_ipp_habitat)
                
#make a distance matrix
p_ipp_matrix_ds=vegdist(p_ipp_matrix, method = 'euclidian')
                
#Run metaMDS on distance matrix
p_ipp_nms=metaMDS(p_ipp_matrix_ds, distance="euclidian",k=2,trymax=500)
p_ipp_nms
#stress=0.045
                
#Run PERMANOVA
pmv_p_ipp = adonis(p_ipp_matrix ~ habitat, data = nmds_p_ipp_habitat, permutations = 999, method = 'euclidean')
pmv_p_ipp
#PERMANOVA Results: Based off of the carotenoid genes being compared
#cyanobacterial strains differ statistically significant 
#between their habitats (p-value:0.023).
#Habitats explian 14.88% of the variance in the copy numbers of critical 
#carotenoid biosynthesis enzymes between cyanobacterial species. 
                
#Visualise the permanova
densityplot(permustats(pmv_p_ipp))
                
#Distance Based Dispersion test 
bd_p_ipp = betadisper(p_ipp_matrix_ds, p_ipp$Habitat)
boxplot(bd_p_ipp)
anova(bd_p_ipp) 
#F-Test: pvalue 0.78
permutest(bd_p_ipp)
#permutation test: pvalue 0.8
#the significance of a permutation test is represented by its P-value. 
#The P-value is the probability of obtaining a result at least 
#as extreme as the test statistic given that the null hypothesis is true. 
                
#both the F-Test and permutation test show that 
#the avergae distance to the median for the 
#habitat data is not statistically significant. 
                
#simper test: determine which genes are responsible for the difference between 2 compared habiatat groups 
simp_p_ipp= simper(p_ipp_matrix, group= p_ipp$Habitat)
summary(simp_p_ipp)
                
#Results of simper test
```